apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: debug
  name: debug
  namespace: test
spec:
  containers:
  - image: quay.io/ajayten/debug-pod:v02
    name: debug
    securityContext:
      capabilities:
        add: ["NET_RAW"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
